(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Kent Williams, created 2009-02-17."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#000055")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "medium turquoise")
      (foreground-color . "#CCBB77")
      (mouse-color . "black"))
     ((goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (rmail-highlight-face . rmail-highlight)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#000055" :foreground "#CCBB77" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :family "apple-monaco"))))
     (bold ((t (:bold t :foreground "#EEDDAA" :weight bold))))
     (bold-italic ((t (:italic t :bold t :foreground "#AA0000" :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (calendar-today-face ((t (:background "darkslategrey" :underline t))))
     (completions-common-part ((t (:family "apple-monaco" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#CCBB77" :background "#000055" :stipple nil :height 120))))
     (completions-first-difference ((t (:bold t :weight bold :foreground "#EEDDAA"))))
     (cperl-array-face ((t (:background "#004060"))))
     (cperl-hash-face ((t (:background "#004400"))))
     (cursor ((t (:background "medium turquoise"))))
     (custom-button-face ((t (:background "dark blue" :foreground "yellow"))))
     (custom-documentation-face ((t (:foreground "#10D010"))))
     (custom-face-tag-face ((t (:foreground "goldenrod" :underline t))))
     (custom-group-tag-face ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-face-1 ((t (:foreground "pink" :underline t))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:foreground "#2020D0"))))
     (custom-state-face ((t (:foreground "mediumaquamarine"))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:foreground "light blue" :underline t))))
     (diary-face ((t (:foreground "red"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:foreground "green"))))
     (eshell-ls-backup-face ((t (:foreground "grey60"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (eshell-ls-executable-face ((t (:foreground "white"))))
     (eshell-ls-missing-face ((t (:foreground "red"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly-face ((t (:foreground "indian red"))))
     (eshell-ls-special-face ((t (:foreground "yellow"))))
     (eshell-ls-symlink-face ((t (:foreground "#6666dd"))))
     (eshell-ls-unreadable-face ((t (:foreground "red"))))
     (eshell-prompt-face ((t (:bold t :background "#305050" :foreground "#EEDD99" :weight bold))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "courier"))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:italic t :bold t :weight bold :slant italic :foreground "grey50"))))
     (font-lock-comment-face ((t (:italic t :bold t :foreground "grey50" :slant italic :weight bold))))
     (font-lock-constant-face ((t (:foreground "indian red"))))
     (font-lock-doc-face ((t (:foreground "#10D010"))))
     (font-lock-function-name-face ((t (:foreground "#D0D000"))))
     (font-lock-keyword-face ((t (:foreground "#00BBBB"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :foreground "#EEDDAA"))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :foreground "#EEDDAA"))))
     (font-lock-string-face ((t (:foreground "#10D010"))))
     (font-lock-type-face ((t (:bold t :foreground "#ff7788" :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "#eeddaa"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (:background "#007080"))))
     (gnus-emphasis-bold ((t (:bold t :foreground "#EEDDAA" :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :foreground "#AA0000" :slant italic :weight bold))))
     (gnus-emphasis-italic ((t (:italic t :foreground "#AA0000" :slant italic))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :foreground "#EEDDAA" :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :foreground "#AA0000" :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :bold t :foreground "#AA0000" :underline t :slant italic :weight bold))))
     (header-line ((t (:box (:line-width 1 :style released-button)))))
     (help-argument-name ((t (:italic t :slant italic :foreground "#AA0000"))))
     (highlight ((t (:background "#226644"))))
     (highlight-changes-delete-face ((t (:background "navy" :foreground "red"))))
     (highlight-changes-face ((t (:background "navy"))))
     (holiday-face ((t (:foreground "#ff7744"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (italic ((t (:italic t :foreground "#AA0000" :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (mac-ts-block-fill-text ((t (:underline t))))
     (mac-ts-caret-position ((t (nil))))
     (mac-ts-converted-text ((t (:underline "gray20"))))
     (mac-ts-no-hilite ((t (:family "apple-monaco" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#CCBB77" :background "#000055" :stipple nil :height 120))))
     (mac-ts-outline-text ((t (:underline t))))
     (mac-ts-raw-text ((t (:underline t))))
     (mac-ts-selected-converted-text ((t (:underline t))))
     (mac-ts-selected-raw-text ((t (:underline t))))
     (mac-ts-selected-text ((t (:underline t))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mode-line ((t (:background "#007080" :foreground "cyan"))))
     (mode-line-buffer-id ((t (:background "#007080" :foreground "cyan"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modeline-mousable ((t (:background "#007080" :foreground "cyan"))))
     (modeline-mousable-minor-mode ((t (:background "#007080" :foreground "cyan"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (:background "#004080"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "#004080"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "darkslategrey"))))
     (sgml-comment-face ((t (:foreground "grey60"))))
     (sgml-doctype-face ((t (:foreground "red"))))
     (sgml-end-tag-face ((t (:foreground "#00D0D0"))))
     (sgml-entity-face ((t (:foreground "indian red"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "green"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "brown"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-start-tag-face ((t (:foreground "#D0D000"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match-face ((t (:background "#400055" :foreground "cyan"))))
     (show-paren-mismatch-face ((t (:background "red"))))
     (special-string-face ((t (:foreground "light green"))))
     (term-black ((t (:background "#000055" :foreground "black"))))
     (term-blackbg ((t (:background "black" :foreground "#CCBB77"))))
     (term-blue ((t (:background "#000055" :foreground "blue"))))
     (term-bluebg ((t (:background "blue" :foreground "#CCBB77"))))
     (term-bold ((t (:bold t :background "#000055" :foreground "#CCBB77" :weight bold))))
     (term-cyan ((t (:background "#000055" :foreground "cyan"))))
     (term-cyanbg ((t (:background "darkcyan"))))
     (term-default-bg ((t (:foreground "#CCBB77"))))
     (term-default-bg-inv ((t (:foreground "#CCBB77"))))
     (term-default-fg ((t (:background "#000055"))))
     (term-default-fg-inv ((t (:background "#000055"))))
     (term-green ((t (:background "#000055" :foreground "green"))))
     (term-greenbg ((t (:background "darkgreen"))))
     (term-invisible ((t (:foreground "#CCBB77"))))
     (term-invisible-inv ((t (:foreground "#CCBB77"))))
     (term-magenta ((t (:background "#000055" :foreground "magenta"))))
     (term-magentabg ((t (:background "darkmagenta"))))
     (term-red ((t (:background "#000055" :foreground "red"))))
     (term-redbg ((t (:background "darkred"))))
     (term-underline ((t (:background "#000055" :foreground "#CCBB77" :underline t))))
     (term-white ((t (:background "#000055" :foreground "white"))))
     (term-whitebg ((t (:background "grey50"))))
     (term-yellow ((t (:background "#000055" :foreground "yellow"))))
     (term-yellowbg ((t (:background "#997700"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "helv" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "#23415A"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "green"))))
     (widget-field ((t (:background "grey35" :foreground "black"))))
     (widget-inactive ((t (:foreground "gray"))))
     (widget-single-line-field ((t (:background "dim gray")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
